# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7e5005b180690bf3b56562a266625a6947f4f41248f9565983d8441f21c2137c8a5b1ca396c34e215e0840047bdd4a92f02e0e9a0063cdcfff024253135e7d

test:
  secret_key_base: bc6418b72dc53e0eb1196c5136371127ae6a67e300b20201cd6aec707ca48a1aa4fcf6c56e1357fdf52c35b3e01185df61551da64a2fe2fd2964256de3baea9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
